### ISSUE TITLE
How to install as a module in DNN?

### ISSUE THREAD

**Issue by ghost** [XCESS-NL/DNNSurvey#3]
How to install it as a module in DNN?

**Comment by serge-van-der-ven** [comment]
As you can see in the Master branch this module has not yet been released as alpha version. In a few days we will push some major changes to the development branch and release an alpha version in the master branch with some instruction on how to install the module in DNN.
Note that it requires the DNN-6802 branch of DNN-Platform to work. The required MVC framework in DNN is not yet available in released DNN Platform editions.

**Comment by ghost** [comment]
You mean the 8.0.0 branch? There's no DNN-6802 branch.

**Comment by serge-van-der-ven** [comment]
You're right. The DNN-6802 branch is already closed and is now part of the 8.0.0 branch.
